include:
  - path: ${BACKEND_PATH:-../../backend/senior-project-smart-ai-web-backend}/compose.yaml
    env_file: ${BACKEND_PATH:-../../backend/senior-project-smart-ai-web-backend}/.env

name: smart-university
